# ~/.config/starship.toml

add_newline = true
command_timeout = 2500
format = """\
[╭─](bright-black) \
$username$hostname$os\
$directory$git_branch\
$cmd_duration
$character"""

[character]
success_symbol = '[\$](bold bright-blue)'
error_symbol = '[\$](bold red)'

####################################################################################################

[username]
disabled = false
show_always = true
style_user = 'bold bright-white'
style_root = 'italic bright-white'
format = '[$user]($style) '

[hostname]
disabled = false
ssh_only = false
style = 'bold bright-blue'
format = 'on [$hostname]($style) '

[os]
disabled = false
format = '[$symbol](bold blue) '
[os.symbols]
Arch = '󰣇'
Linux = ''
Ubuntu = ''
Fedora = '󰣛'
Debian = '󰣚'
Macos = '󰀵'
Windows = '󰖳'

[directory]
truncation_length = 1
truncation_symbol = '…/'
home_symbol = ' ~'
read_only_style = '197'
read_only = '  '
style = 'bold cyan'
format = 'at [$path]($style)[$read_only]($read_only_style) '

[git_branch]
truncation_length = 20
truncation_symbol = '…/'
symbol = ' '
style = 'bold white'
format = 'via [$symbol$branch]($style) '

[cmd_duration]
min_time = 0
