# ~/.config/starship.toml

add_newline = false
command_timeout = 2500
format = """\
[╭─](bright-black) $os$directory$git_branch$python$cmd_duration
$character"""

[character]
success_symbol = '[\$](bold bright-blue)'
error_symbol = '[\$](bold red)'

[profiles]
transient = '[\$](bold purple) '

####################################################################################################

[os]
disabled = false
format = '[$symbol](bold blue) '
[os.symbols]
Arch = '󰣇'
Linux = ''
Ubuntu = ''
Fedora = '󰣛'
Debian = '󰣚'
Macos = '󰀵'
Windows = '󰖳'

[directory]
truncation_length = 1
truncation_symbol = '…/'
home_symbol = ' ~'
read_only_style = '197'
read_only = '  '
style = 'bold bright-blue'
format = 'at [$path]($style)[$read_only]($read_only_style) '

[git_branch]
truncation_length = 20
truncation_symbol = '…/'
symbol = ' '
style = 'bold bright-cyan'
format = 'via [$symbol$branch]($style) '

[python]
symbol = ' '
style = 'bold bright-purple'
format = 'in [$symbol$virtualenv]($style) '
detect_extensions = []
detect_files = []
detect_folders = []

[cmd_duration]
style = 'bold bright-red'
format = 'took [$duration]($style) '
min_time = 0
show_milliseconds = true
